language: node_js
node_js: '8'

cache: yarn
install:
  - yarn install

jobs:
  include:
    - stage: test
      before_install:
      - yarn global add greenkeeper-lockfile@1
      before_script:
        # Determine if a greenkeeper package update
        # This is a null op if not on `greenkeeper/*` branch
        - greenkeeper-lockfile-update
        - yarn run build
      script: 
        - commitlint-travis
        - yarn run lint
        - yarn run test
      after_script:
        - greenkeeper-lockfile-upload
        - bash <(curl -s https://codecov.io/bash) # Upload code coverage reports
    - stage: NPM Publish Release
      if: NOT type IN (pull_request) AND branch IN (master, dev)
      git: # Allow us to checkout Branch
        depth: false
      before_script:
        - git checkout $TRAVIS_BRANCH
      deploy:
        - provider: script
          skip_cleanup: true
          script:
            - yarn run publish --yes
          on:
            branch: master
        - provider: script
          skip_cleanup: true
          script:
            - yarn run publish --yes --cd-verison prerelease
          on:
            branch: dev