language: node_js
node_js: '8'

install:
  - yarn install

jobs:
  include:
    - stage: test
      before_install:
      - yarn global add greenkeeper-lockfile@1
      before_script:
        # Determine if a greenkeeper package update
        # This is a null op if not on `greenkeeper/*` branch
        - greenkeeper-lockfile-update
        - yarn run build
      script: 
        - yarn run lint
        - yarn run test
      after_script:
        - greenkeeper-lockfile-upload
        - bash <(curl -s https://codecov.io/bash) # Upload code coverage reports
    - stage: release
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn run semantic-release
