version: '3'

services:
  all:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home
      - node_modules:/home/node_modules
  heartwood:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./packages/heartwood-components:/home
      - heartwood-components:/home/node_modules
  react-heartwood:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./packages/react-heartwood-components:/home
      - react-heartwood-components:/home/node_modules

volumes:
  react-heartwood-components:
  heartwood-components:
  node_modules:
