// flow-typed signature: b765bfd854079aa3411e8f9ed4d05773
// flow-typed version: <<STUB>>/blueimp-canvas-to-blob_v^3.14.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blueimp-canvas-to-blob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blueimp-canvas-to-blob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blueimp-canvas-to-blob/js/canvas-to-blob' {
  declare module.exports: any;
}

declare module 'blueimp-canvas-to-blob/js/canvas-to-blob.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blueimp-canvas-to-blob/js/canvas-to-blob.js' {
  declare module.exports: $Exports<'blueimp-canvas-to-blob/js/canvas-to-blob'>;
}
declare module 'blueimp-canvas-to-blob/js/canvas-to-blob.min.js' {
  declare module.exports: $Exports<'blueimp-canvas-to-blob/js/canvas-to-blob.min'>;
}
