// flow-typed signature: fbb9873500e7fa94442631bfb34ef5ec
// flow-typed version: <<STUB>>/cookies_v^0.7.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cookies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cookies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cookies/index' {
  declare module.exports: $Exports<'cookies'>;
}
declare module 'cookies/index.js' {
  declare module.exports: $Exports<'cookies'>;
}
