// flow-typed signature: 9ec0d0a7ef1015eee0462cc8ed9ceeb8
// flow-typed version: <<STUB>>/es6-tween_v^5.3.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-tween'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-tween' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es6-tween/bundled/Tween' {
  declare module.exports: any;
}

declare module 'es6-tween/bundled/Tween.min' {
  declare module.exports: any;
}

declare module 'es6-tween/rollup.config' {
  declare module.exports: any;
}

declare module 'es6-tween/src/constants' {
  declare module.exports: any;
}

declare module 'es6-tween/src/core' {
  declare module.exports: any;
}

declare module 'es6-tween/src/Easing' {
  declare module.exports: any;
}

declare module 'es6-tween/src/index' {
  declare module.exports: any;
}

declare module 'es6-tween/src/Interpolation' {
  declare module.exports: any;
}

declare module 'es6-tween/src/Interpolator' {
  declare module.exports: any;
}

declare module 'es6-tween/src/NodeCache' {
  declare module.exports: any;
}

declare module 'es6-tween/src/PlaybackPosition' {
  declare module.exports: any;
}

declare module 'es6-tween/src/selector' {
  declare module.exports: any;
}

declare module 'es6-tween/src/shim' {
  declare module.exports: any;
}

declare module 'es6-tween/src/Tween' {
  declare module.exports: any;
}

declare module 'es6-tween/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es6-tween/bundled/Tween.js' {
  declare module.exports: $Exports<'es6-tween/bundled/Tween'>;
}
declare module 'es6-tween/bundled/Tween.min.js' {
  declare module.exports: $Exports<'es6-tween/bundled/Tween.min'>;
}
declare module 'es6-tween/rollup.config.js' {
  declare module.exports: $Exports<'es6-tween/rollup.config'>;
}
declare module 'es6-tween/src/constants.js' {
  declare module.exports: $Exports<'es6-tween/src/constants'>;
}
declare module 'es6-tween/src/core.js' {
  declare module.exports: $Exports<'es6-tween/src/core'>;
}
declare module 'es6-tween/src/Easing.js' {
  declare module.exports: $Exports<'es6-tween/src/Easing'>;
}
declare module 'es6-tween/src/index.js' {
  declare module.exports: $Exports<'es6-tween/src/index'>;
}
declare module 'es6-tween/src/Interpolation.js' {
  declare module.exports: $Exports<'es6-tween/src/Interpolation'>;
}
declare module 'es6-tween/src/Interpolator.js' {
  declare module.exports: $Exports<'es6-tween/src/Interpolator'>;
}
declare module 'es6-tween/src/NodeCache.js' {
  declare module.exports: $Exports<'es6-tween/src/NodeCache'>;
}
declare module 'es6-tween/src/PlaybackPosition.js' {
  declare module.exports: $Exports<'es6-tween/src/PlaybackPosition'>;
}
declare module 'es6-tween/src/selector.js' {
  declare module.exports: $Exports<'es6-tween/src/selector'>;
}
declare module 'es6-tween/src/shim.js' {
  declare module.exports: $Exports<'es6-tween/src/shim'>;
}
declare module 'es6-tween/src/Tween.js' {
  declare module.exports: $Exports<'es6-tween/src/Tween'>;
}
declare module 'es6-tween/test.js' {
  declare module.exports: $Exports<'es6-tween/test'>;
}
