// flow-typed signature: 62653c5e9284d576b7f5e9836015c8bc
// flow-typed version: <<STUB>>/exif-orientation-image_v^1.0.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exif-orientation-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exif-orientation-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exif-orientation-image/index' {
  declare module.exports: $Exports<'exif-orientation-image'>;
}
declare module 'exif-orientation-image/index.js' {
  declare module.exports: $Exports<'exif-orientation-image'>;
}
