// flow-typed signature: 6e9be198163b65eb2f2ea9cd38b85319
// flow-typed version: <<STUB>>/is_js_v^0.9.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is_js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is_js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is_js/is' {
  declare module.exports: any;
}

declare module 'is_js/is.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is_js/is.js' {
  declare module.exports: $Exports<'is_js/is'>;
}
declare module 'is_js/is.min.js' {
  declare module.exports: $Exports<'is_js/is.min'>;
}
