// flow-typed signature: 9a1f2dc7ca8bc12376dbad857547aedb
// flow-typed version: <<STUB>>/js-cookies_v^1.0.4/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-cookies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-cookies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-cookies/src/cookies' {
  declare module.exports: any;
}

declare module 'js-cookies/test/cookies.spec' {
  declare module.exports: any;
}

declare module 'js-cookies/webpack.tests.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-cookies/index' {
  declare module.exports: $Exports<'js-cookies'>;
}
declare module 'js-cookies/index.js' {
  declare module.exports: $Exports<'js-cookies'>;
}
declare module 'js-cookies/src/cookies.js' {
  declare module.exports: $Exports<'js-cookies/src/cookies'>;
}
declare module 'js-cookies/test/cookies.spec.js' {
  declare module.exports: $Exports<'js-cookies/test/cookies.spec'>;
}
declare module 'js-cookies/webpack.tests.config.js' {
  declare module.exports: $Exports<'js-cookies/webpack.tests.config'>;
}
