// flow-typed signature: 722ac06df985bfa3a15b2f6dbbbe1130
// flow-typed version: <<STUB>>/velocity-react_v^1.4.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'velocity-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'velocity-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'velocity-react/lib/velocity-animate-shim' {
  declare module.exports: any;
}

declare module 'velocity-react/src/index' {
  declare module.exports: any;
}

declare module 'velocity-react/src/lib/velocity-animate-shim' {
  declare module.exports: any;
}

declare module 'velocity-react/src/velocity-component' {
  declare module.exports: any;
}

declare module 'velocity-react/src/velocity-helpers' {
  declare module.exports: any;
}

declare module 'velocity-react/src/velocity-transition-group' {
  declare module.exports: any;
}

declare module 'velocity-react/velocity-component' {
  declare module.exports: any;
}

declare module 'velocity-react/velocity-helpers' {
  declare module.exports: any;
}

declare module 'velocity-react/velocity-transition-group' {
  declare module.exports: any;
}

// Filename aliases
declare module 'velocity-react/index' {
  declare module.exports: $Exports<'velocity-react'>;
}
declare module 'velocity-react/index.js' {
  declare module.exports: $Exports<'velocity-react'>;
}
declare module 'velocity-react/lib/velocity-animate-shim.js' {
  declare module.exports: $Exports<'velocity-react/lib/velocity-animate-shim'>;
}
declare module 'velocity-react/src/index.js' {
  declare module.exports: $Exports<'velocity-react/src/index'>;
}
declare module 'velocity-react/src/lib/velocity-animate-shim.js' {
  declare module.exports: $Exports<'velocity-react/src/lib/velocity-animate-shim'>;
}
declare module 'velocity-react/src/velocity-component.js' {
  declare module.exports: $Exports<'velocity-react/src/velocity-component'>;
}
declare module 'velocity-react/src/velocity-helpers.js' {
  declare module.exports: $Exports<'velocity-react/src/velocity-helpers'>;
}
declare module 'velocity-react/src/velocity-transition-group.js' {
  declare module.exports: $Exports<'velocity-react/src/velocity-transition-group'>;
}
declare module 'velocity-react/velocity-component.js' {
  declare module.exports: $Exports<'velocity-react/velocity-component'>;
}
declare module 'velocity-react/velocity-helpers.js' {
  declare module.exports: $Exports<'velocity-react/velocity-helpers'>;
}
declare module 'velocity-react/velocity-transition-group.js' {
  declare module.exports: $Exports<'velocity-react/velocity-transition-group'>;
}
