version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'ee:61:04:89:80:2e:f3:ac:3f:88:6a:ce:52:33:86:4e'
      - checkout
      - run: yarn install
      - run: yarn test
  pre_release:
    docker:
      - image: circleci/node:8
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'ee:61:04:89:80:2e:f3:ac:3f:88:6a:ce:52:33:86:4e'
      - checkout
      - run: yarn install
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: yarn run publish --yes --canary --preid pre --message "%s [skip ci]"
  dev_release:
    docker:
      - image: circleci/node:8
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'ee:61:04:89:80:2e:f3:ac:3f:88:6a:ce:52:33:86:4e'
      - checkout
      - run: yarn install
      - run: git config --global user.email "$GIT_AUTHOR_EMAIL"
      - run: git config --global user.name "$GIT_AUTHOR_NAME"
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: yarn run publish --yes --force-publish --npm-tag beta --message "%s [skip ci]"
  prod_release:
    docker:
      - image: circleci/node:8
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'ee:61:04:89:80:2e:f3:ac:3f:88:6a:ce:52:33:86:4e'
      - checkout
      - run: yarn install
      - run: git config --global user.email "$GIT_AUTHOR_EMAIL"
      - run: git config --global user.name "$GIT_AUTHOR_NAME"
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npx lerna exec --no-bail --no-private --no-sort --stream -- '[ -n "$(npm v . dist-tags.beta)" ] && npm dist-tag add ${LERNA_PACKAGE_NAME}@$(npm v . dist-tags.beta) latest'
workflows:
  version: 2
  do_build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
      - pre_release:
          requires:
            - test
          filters:
            branches:
              only:
                - /prerelease\/.*/
      - dev_release:
          requires:
            - test
          filters:
            branches:
              only:
                - dev
      - prod_release:
          filters:
            branches:
              only:
                - master
