const Classes = require('../../classes')

module.exports = {
	title: 'Autosuggest',
	collated: true,
	collator: function(markup, item) {
		return `<!-- Start: @${
			item.handle
		} -->\n<div style="margin-bottom: 1rem;">${markup}</div>\n<!-- End: @${
			item.handle
		} -->\n`
	},
	context: {
		Classes: Classes,
		label: 'Country',
		placeholder: 'Select your Country',
		options: [
			{ text: 'Afghanistan', Classes: Classes },
			{ text: 'Aland Islands', Classes: Classes },
			{ text: 'Albania', Classes: Classes },
			{ text: 'Algeria', Classes: Classes },
			{ text: 'Andorra', Classes: Classes },
			{ text: 'Angola', Classes: Classes },
			{ text: 'Anguilla', Classes: Classes },
			{ text: 'Antigua And Barbuda', Classes: Classes },
			{ text: 'Argentina', Classes: Classes },
			{ text: 'Armenia', Classes: Classes },
			{ text: 'Aruba', Classes: Classes },
			{ text: 'Australia', Classes: Classes },
			{ text: 'Austria', Classes: Classes },
			{ text: 'Azerbaijan', Classes: Classes },
			{ text: 'Bahamas', Classes: Classes },
			{ text: 'Bahrain', Classes: Classes },
			{ text: 'Bangladesh', Classes: Classes },
			{ text: 'Barbados', Classes: Classes },
			{ text: 'Belarus', Classes: Classes },
			{ text: 'Belgium', Classes: Classes },
			{ text: 'Belize', Classes: Classes },
			{ text: 'Benin', Classes: Classes },
			{ text: 'Bermuda', Classes: Classes },
			{ text: 'Bhutan', Classes: Classes },
			{ text: 'Bolivia', Classes: Classes },
			{ text: 'Bonaire, Sint Eustatius and Saba', Classes: Classes },
			{ text: 'Bosnia And Herzegovina', Classes: Classes },
			{ text: 'Botswana', Classes: Classes },
			{ text: 'Bouvet Island', Classes: Classes },
			{ text: 'Brazil', Classes: Classes },
			{ text: 'British Indian Ocean Territory', Classes: Classes },
			{ text: 'Brunei', Classes: Classes },
			{ text: 'Bulgaria', Classes: Classes },
			{ text: 'Burkina Faso', Classes: Classes },
			{ text: 'Burundi', Classes: Classes },
			{ text: 'Cambodia', Classes: Classes },
			{ text: 'Canada', Classes: Classes },
			{ text: 'Cape Verde', Classes: Classes },
			{ text: 'Cayman Islands', Classes: Classes },
			{ text: 'Central African Republic', Classes: Classes },
			{ text: 'Chad', Classes: Classes },
			{ text: 'Chile', Classes: Classes },
			{ text: 'China', Classes: Classes },
			{ text: 'Christmas Island', Classes: Classes },
			{ text: 'Cocos (Keeling) Islands', Classes: Classes },
			{ text: 'Colombia', Classes: Classes },
			{ text: 'Comoros', Classes: Classes },
			{ text: 'Congo', Classes: Classes },
			{ text: 'Congo, The Democratic Republic Of The', Classes: Classes },
			{ text: 'Cook Islands', Classes: Classes },
			{ text: 'Costa Rica', Classes: Classes },
			{ text: 'Croatia', Classes: Classes },
			{ text: 'Cuba', Classes: Classes },
			{ text: 'Curaçao', Classes: Classes },
			{ text: 'Cyprus', Classes: Classes },
			{ text: 'Czech Republic', Classes: Classes },
			{ text: "Côte d'Ivoire", Classes: Classes },
			{ text: 'Denmark', Classes: Classes },
			{ text: 'Djibouti', Classes: Classes },
			{ text: 'Dominica', Classes: Classes },
			{ text: 'Dominican Republic', Classes: Classes },
			{ text: 'Ecuador', Classes: Classes },
			{ text: 'Egypt', Classes: Classes },
			{ text: 'El Salvador', Classes: Classes },
			{ text: 'Equatorial Guinea', Classes: Classes },
			{ text: 'Eritrea', Classes: Classes },
			{ text: 'Estonia', Classes: Classes },
			{ text: 'Ethiopia', Classes: Classes },
			{ text: 'Falkland Islands (Malvinas)', Classes: Classes },
			{ text: 'Faroe Islands', Classes: Classes },
			{ text: 'Fiji', Classes: Classes },
			{ text: 'Finland', Classes: Classes },
			{ text: 'France', Classes: Classes },
			{ text: 'French Guiana', Classes: Classes },
			{ text: 'French Polynesia', Classes: Classes },
			{ text: 'French Southern Territories', Classes: Classes },
			{ text: 'Gabon', Classes: Classes },
			{ text: 'Gambia', Classes: Classes },
			{ text: 'Georgia', Classes: Classes },
			{ text: 'Germany', Classes: Classes },
			{ text: 'Ghana', Classes: Classes },
			{ text: 'Gibraltar', Classes: Classes },
			{ text: 'Greece', Classes: Classes },
			{ text: 'Greenland', Classes: Classes },
			{ text: 'Grenada', Classes: Classes },
			{ text: 'Guadeloupe', Classes: Classes },
			{ text: 'Guatemala', Classes: Classes },
			{ text: 'Guernsey', Classes: Classes },
			{ text: 'Guinea', Classes: Classes },
			{ text: 'Guinea Bissau', Classes: Classes },
			{ text: 'Guyana', Classes: Classes },
			{ text: 'Haiti', Classes: Classes },
			{ text: 'Heard Island And Mcdonald Islands', Classes: Classes },
			{ text: 'Holy See (Vatican City State)', Classes: Classes },
			{ text: 'Honduras', Classes: Classes },
			{ text: 'Hong Kong', Classes: Classes },
			{ text: 'Hungary', Classes: Classes },
			{ text: 'Iceland', Classes: Classes },
			{ text: 'India', Classes: Classes },
			{ text: 'Indonesia', Classes: Classes },
			{ text: 'Iran, Islamic Republic Of', Classes: Classes },
			{ text: 'Iraq', Classes: Classes },
			{ text: 'Ireland', Classes: Classes },
			{ text: 'Isle Of Man', Classes: Classes },
			{ text: 'Israel', Classes: Classes },
			{ text: 'Italy', Classes: Classes },
			{ text: 'Jamaica', Classes: Classes },
			{ text: 'Japan', Classes: Classes },
			{ text: 'Jersey', Classes: Classes },
			{ text: 'Jordan', Classes: Classes },
			{ text: 'Kazakhstan', Classes: Classes },
			{ text: 'Kenya', Classes: Classes },
			{ text: 'Kiribati', Classes: Classes },
			{ text: "Korea, Democratic People's Republic Of", Classes: Classes },
			{ text: 'Kosovo', Classes: Classes },
			{ text: 'Kuwait', Classes: Classes },
			{ text: 'Kyrgyzstan', Classes: Classes },
			{ text: "Lao People's Democratic Republic", Classes: Classes },
			{ text: 'Latvia', Classes: Classes },
			{ text: 'Lebanon', Classes: Classes },
			{ text: 'Lesotho', Classes: Classes },
			{ text: 'Liberia', Classes: Classes },
			{ text: 'Libyan Arab Jamahiriya', Classes: Classes },
			{ text: 'Liechtenstein', Classes: Classes },
			{ text: 'Lithuania', Classes: Classes },
			{ text: 'Luxembourg', Classes: Classes },
			{ text: 'Macao', Classes: Classes },
			{ text: 'Macedonia, Republic Of', Classes: Classes },
			{ text: 'Madagascar', Classes: Classes },
			{ text: 'Malawi', Classes: Classes },
			{ text: 'Malaysia', Classes: Classes },
			{ text: 'Maldives', Classes: Classes },
			{ text: 'Mali', Classes: Classes },
			{ text: 'Malta', Classes: Classes },
			{ text: 'Martinique', Classes: Classes },
			{ text: 'Mauritania', Classes: Classes },
			{ text: 'Mauritius', Classes: Classes },
			{ text: 'Mayotte', Classes: Classes },
			{ text: 'Mexico', Classes: Classes },
			{ text: 'Moldova, Republic of', Classes: Classes },
			{ text: 'Monaco', Classes: Classes },
			{ text: 'Mongolia', Classes: Classes },
			{ text: 'Montenegro', Classes: Classes },
			{ text: 'Montserrat', Classes: Classes },
			{ text: 'Morocco', Classes: Classes },
			{ text: 'Mozambique', Classes: Classes },
			{ text: 'Myanmar', Classes: Classes },
			{ text: 'Namibia', Classes: Classes },
			{ text: 'Nauru', Classes: Classes },
			{ text: 'Nepal', Classes: Classes },
			{ text: 'Netherlands', Classes: Classes },
			{ text: 'Netherlands Antilles', Classes: Classes },
			{ text: 'New Caledonia', Classes: Classes },
			{ text: 'New Zealand', Classes: Classes },
			{ text: 'Nicaragua', Classes: Classes },
			{ text: 'Niger', Classes: Classes },
			{ text: 'Nigeria', Classes: Classes },
			{ text: 'Niue', Classes: Classes },
			{ text: 'Norfolk Island', Classes: Classes },
			{ text: 'Norway', Classes: Classes },
			{ text: 'Oman', Classes: Classes },
			{ text: 'Pakistan', Classes: Classes },
			{ text: 'Palestinian Territory, Occupied', Classes: Classes },
			{ text: 'Panama', Classes: Classes },
			{ text: 'Papua New Guinea', Classes: Classes },
			{ text: 'Paraguay', Classes: Classes },
			{ text: 'Peru', Classes: Classes },
			{ text: 'Philippines', Classes: Classes },
			{ text: 'Pitcairn', Classes: Classes },
			{ text: 'Poland', Classes: Classes },
			{ text: 'Portugal', Classes: Classes },
			{ text: 'Qatar', Classes: Classes },
			{ text: 'Republic of Cameroon', Classes: Classes },
			{ text: 'Reunion', Classes: Classes },
			{ text: 'Romania', Classes: Classes },
			{ text: 'Russia', Classes: Classes },
			{ text: 'Rwanda', Classes: Classes },
			{ text: 'Saint Barthélemy', Classes: Classes },
			{ text: 'Saint Helena', Classes: Classes },
			{ text: 'Saint Kitts And Nevis', Classes: Classes },
			{ text: 'Saint Lucia', Classes: Classes },
			{ text: 'Saint Martin', Classes: Classes },
			{ text: 'Saint Pierre And Miquelon', Classes: Classes },
			{ text: 'Samoa', Classes: Classes },
			{ text: 'San Marino', Classes: Classes },
			{ text: 'Sao Tome And Principe', Classes: Classes },
			{ text: 'Saudi Arabia', Classes: Classes },
			{ text: 'Senegal', Classes: Classes },
			{ text: 'Serbia', Classes: Classes },
			{ text: 'Seychelles', Classes: Classes },
			{ text: 'Sierra Leone', Classes: Classes },
			{ text: 'Singapore', Classes: Classes },
			{ text: 'Sint Maarten', Classes: Classes },
			{ text: 'Slovakia', Classes: Classes },
			{ text: 'Slovenia', Classes: Classes },
			{ text: 'Solomon Islands', Classes: Classes },
			{ text: 'Somalia', Classes: Classes },
			{ text: 'South Africa', Classes: Classes },
			{
				text: 'South Georgia And The South Sandwich Islands',
				Classes: Classes
			},
			{ text: 'South Korea', Classes: Classes },
			{ text: 'South Sudan', Classes: Classes },
			{ text: 'Spain', Classes: Classes },
			{ text: 'Sri Lanka', Classes: Classes },
			{ text: 'St. Vincent', Classes: Classes },
			{ text: 'Sudan', Classes: Classes },
			{ text: 'Suriname', Classes: Classes },
			{ text: 'Svalbard And Jan Mayen', Classes: Classes },
			{ text: 'Swaziland', Classes: Classes },
			{ text: 'Sweden', Classes: Classes },
			{ text: 'Switzerland', Classes: Classes },
			{ text: 'Syria', Classes: Classes },
			{ text: 'Taiwan', Classes: Classes },
			{ text: 'Tajikistan', Classes: Classes },
			{ text: 'Tanzania, United Republic Of', Classes: Classes },
			{ text: 'Thailand', Classes: Classes },
			{ text: 'Timor Leste', Classes: Classes },
			{ text: 'Togo', Classes: Classes },
			{ text: 'Tokelau', Classes: Classes },
			{ text: 'Tonga', Classes: Classes },
			{ text: 'Trinidad and Tobago', Classes: Classes },
			{ text: 'Tunisia', Classes: Classes },
			{ text: 'Turkey', Classes: Classes },
			{ text: 'Turkmenistan', Classes: Classes },
			{ text: 'Turks and Caicos Islands', Classes: Classes },
			{ text: 'Tuvalu', Classes: Classes },
			{ text: 'Uganda', Classes: Classes },
			{ text: 'Ukraine', Classes: Classes },
			{ text: 'United Arab Emirates', Classes: Classes },
			{ text: 'United Kingdom', Classes: Classes },
			{ text: 'elected" value="US">United States', Classes: Classes },
			{ text: 'United States Minor Outlying Islands', Classes: Classes },
			{ text: 'Uruguay', Classes: Classes },
			{ text: 'Uzbekistan', Classes: Classes },
			{ text: 'Vanuatu', Classes: Classes },
			{ text: 'Venezuela', Classes: Classes },
			{ text: 'Vietnam', Classes: Classes },
			{ text: 'Virgin Islands, British', Classes: Classes },
			{ text: 'Wallis And Futuna', Classes: Classes },
			{ text: 'Western Sahara', Classes: Classes },
			{ text: 'Yemen', Classes: Classes },
			{ text: 'Zambia', Classes: Classes },
			{ text: 'Zimbabwe', Classes: Classes }
		]
	},
	variants: [
		{
			name: 'No Results',
			label: 'Country',
			placeholder: 'Select your Country',
			context: {
				Classes: Classes,
				options: null
			}
		}
	]
}
