module.exports = {
	title: 'Autosuggest',
	collated: true,
	collator: function(markup, item) {
		return `<!-- Start: @${item.handle} -->\n<div style="margin-top: 1rem;">${markup}</div>\n<!-- End: @${item.handle} -->\n`
	},
	context: {
		label: 'Country',
		placeholder: 'Select your Country',
		options: [
			{ text: 'Afghanistan' },
			{ text: 'Aland Islands' },
			{ text: 'Albania' },
			{ text: 'Algeria' },
			{ text: 'Andorra' },
			{ text: 'Angola' },
			{ text: 'Anguilla' },
			{ text: 'Antigua And Barbuda' },
			{ text: 'Argentina' },
			{ text: 'Armenia' },
			{ text: 'Aruba' },
			{ text: 'Australia' },
			{ text: 'Austria' },
			{ text: 'Azerbaijan' },
			{ text: 'Bahamas' },
			{ text: 'Bahrain' },
			{ text: 'Bangladesh' },
			{ text: 'Barbados' },
			{ text: 'Belarus' },
			{ text: 'Belgium' },
			{ text: 'Belize' },
			{ text: 'Benin' },
			{ text: 'Bermuda' },
			{ text: 'Bhutan' },
			{ text: 'Bolivia' },
			{ text: 'Bonaire, Sint Eustatius and Saba' },
			{ text: 'Bosnia And Herzegovina' },
			{ text: 'Botswana' },
			{ text: 'Bouvet Island' },
			{ text: 'Brazil' },
			{ text: 'British Indian Ocean Territory' },
			{ text: 'Brunei' },
			{ text: 'Bulgaria' },
			{ text: 'Burkina Faso' },
			{ text: 'Burundi' },
			{ text: 'Cambodia' },
			{ text: 'Canada' },
			{ text: 'Cape Verde' },
			{ text: 'Cayman Islands' },
			{ text: 'Central African Republic' },
			{ text: 'Chad' },
			{ text: 'Chile' },
			{ text: 'China' },
			{ text: 'Christmas Island' },
			{ text: 'Cocos (Keeling) Islands' },
			{ text: 'Colombia' },
			{ text: 'Comoros' },
			{ text: 'Congo' },
			{ text: 'Congo, The Democratic Republic Of The' },
			{ text: 'Cook Islands' },
			{ text: 'Costa Rica' },
			{ text: 'Croatia' },
			{ text: 'Cuba' },
			{ text: 'Curaçao' },
			{ text: 'Cyprus' },
			{ text: 'Czech Republic' },
			{ text: "Côte d'Ivoire" },
			{ text: 'Denmark' },
			{ text: 'Djibouti' },
			{ text: 'Dominica' },
			{ text: 'Dominican Republic' },
			{ text: 'Ecuador' },
			{ text: 'Egypt' },
			{ text: 'El Salvador' },
			{ text: 'Equatorial Guinea' },
			{ text: 'Eritrea' },
			{ text: 'Estonia' },
			{ text: 'Ethiopia' },
			{ text: 'Falkland Islands (Malvinas)' },
			{ text: 'Faroe Islands' },
			{ text: 'Fiji' },
			{ text: 'Finland' },
			{ text: 'France' },
			{ text: 'French Guiana' },
			{ text: 'French Polynesia' },
			{ text: 'French Southern Territories' },
			{ text: 'Gabon' },
			{ text: 'Gambia' },
			{ text: 'Georgia' },
			{ text: 'Germany' },
			{ text: 'Ghana' },
			{ text: 'Gibraltar' },
			{ text: 'Greece' },
			{ text: 'Greenland' },
			{ text: 'Grenada' },
			{ text: 'Guadeloupe' },
			{ text: 'Guatemala' },
			{ text: 'Guernsey' },
			{ text: 'Guinea' },
			{ text: 'Guinea Bissau' },
			{ text: 'Guyana' },
			{ text: 'Haiti' },
			{ text: 'Heard Island And Mcdonald Islands' },
			{ text: 'Holy See (Vatican City State)' },
			{ text: 'Honduras' },
			{ text: 'Hong Kong' },
			{ text: 'Hungary' },
			{ text: 'Iceland' },
			{ text: 'India' },
			{ text: 'Indonesia' },
			{ text: 'Iran, Islamic Republic Of' },
			{ text: 'Iraq' },
			{ text: 'Ireland' },
			{ text: 'Isle Of Man' },
			{ text: 'Israel' },
			{ text: 'Italy' },
			{ text: 'Jamaica' },
			{ text: 'Japan' },
			{ text: 'Jersey' },
			{ text: 'Jordan' },
			{ text: 'Kazakhstan' },
			{ text: 'Kenya' },
			{ text: 'Kiribati' },
			{ text: "Korea, Democratic People's Republic Of" },
			{ text: 'Kosovo' },
			{ text: 'Kuwait' },
			{ text: 'Kyrgyzstan' },
			{ text: "Lao People's Democratic Republic" },
			{ text: 'Latvia' },
			{ text: 'Lebanon' },
			{ text: 'Lesotho' },
			{ text: 'Liberia' },
			{ text: 'Libyan Arab Jamahiriya' },
			{ text: 'Liechtenstein' },
			{ text: 'Lithuania' },
			{ text: 'Luxembourg' },
			{ text: 'Macao' },
			{ text: 'Macedonia, Republic Of' },
			{ text: 'Madagascar' },
			{ text: 'Malawi' },
			{ text: 'Malaysia' },
			{ text: 'Maldives' },
			{ text: 'Mali' },
			{ text: 'Malta' },
			{ text: 'Martinique' },
			{ text: 'Mauritania' },
			{ text: 'Mauritius' },
			{ text: 'Mayotte' },
			{ text: 'Mexico' },
			{ text: 'Moldova, Republic of' },
			{ text: 'Monaco' },
			{ text: 'Mongolia' },
			{ text: 'Montenegro' },
			{ text: 'Montserrat' },
			{ text: 'Morocco' },
			{ text: 'Mozambique' },
			{ text: 'Myanmar' },
			{ text: 'Namibia' },
			{ text: 'Nauru' },
			{ text: 'Nepal' },
			{ text: 'Netherlands' },
			{ text: 'Netherlands Antilles' },
			{ text: 'New Caledonia' },
			{ text: 'New Zealand' },
			{ text: 'Nicaragua' },
			{ text: 'Niger' },
			{ text: 'Nigeria' },
			{ text: 'Niue' },
			{ text: 'Norfolk Island' },
			{ text: 'Norway' },
			{ text: 'Oman' },
			{ text: 'Pakistan' },
			{ text: 'Palestinian Territory, Occupied' },
			{ text: 'Panama' },
			{ text: 'Papua New Guinea' },
			{ text: 'Paraguay' },
			{ text: 'Peru' },
			{ text: 'Philippines' },
			{ text: 'Pitcairn' },
			{ text: 'Poland' },
			{ text: 'Portugal' },
			{ text: 'Qatar' },
			{ text: 'Republic of Cameroon' },
			{ text: 'Reunion' },
			{ text: 'Romania' },
			{ text: 'Russia' },
			{ text: 'Rwanda' },
			{ text: 'Saint Barthélemy' },
			{ text: 'Saint Helena' },
			{ text: 'Saint Kitts And Nevis' },
			{ text: 'Saint Lucia' },
			{ text: 'Saint Martin' },
			{ text: 'Saint Pierre And Miquelon' },
			{ text: 'Samoa' },
			{ text: 'San Marino' },
			{ text: 'Sao Tome And Principe' },
			{ text: 'Saudi Arabia' },
			{ text: 'Senegal' },
			{ text: 'Serbia' },
			{ text: 'Seychelles' },
			{ text: 'Sierra Leone' },
			{ text: 'Singapore' },
			{ text: 'Sint Maarten' },
			{ text: 'Slovakia' },
			{ text: 'Slovenia' },
			{ text: 'Solomon Islands' },
			{ text: 'Somalia' },
			{ text: 'South Africa' },
			{ text: 'South Georgia And The South Sandwich Islands' },
			{ text: 'South Korea' },
			{ text: 'South Sudan' },
			{ text: 'Spain' },
			{ text: 'Sri Lanka' },
			{ text: 'St. Vincent' },
			{ text: 'Sudan' },
			{ text: 'Suriname' },
			{ text: 'Svalbard And Jan Mayen' },
			{ text: 'Swaziland' },
			{ text: 'Sweden' },
			{ text: 'Switzerland' },
			{ text: 'Syria' },
			{ text: 'Taiwan' },
			{ text: 'Tajikistan' },
			{ text: 'Tanzania, United Republic Of' },
			{ text: 'Thailand' },
			{ text: 'Timor Leste' },
			{ text: 'Togo' },
			{ text: 'Tokelau' },
			{ text: 'Tonga' },
			{ text: 'Trinidad and Tobago' },
			{ text: 'Tunisia' },
			{ text: 'Turkey' },
			{ text: 'Turkmenistan' },
			{ text: 'Turks and Caicos Islands' },
			{ text: 'Tuvalu' },
			{ text: 'Uganda' },
			{ text: 'Ukraine' },
			{ text: 'United Arab Emirates' },
			{ text: 'United Kingdom' },
			{ text: 'elected" value="US">United States' },
			{ text: 'United States Minor Outlying Islands' },
			{ text: 'Uruguay' },
			{ text: 'Uzbekistan' },
			{ text: 'Vanuatu' },
			{ text: 'Venezuela' },
			{ text: 'Vietnam' },
			{ text: 'Virgin Islands, British' },
			{ text: 'Wallis And Futuna' },
			{ text: 'Western Sahara' },
			{ text: 'Yemen' },
			{ text: 'Zambia' },
			{ text: 'Zimbabwe' }
		]
	},
	variants: [
		{
			name: 'No Results',
			label: 'Country',
			placeholder: 'Select your Country',
			context: {
				options: null
			}
		}
	]
}
