// flow-typed signature: f001d7f33b0f803a084c4ba765f21851
// flow-typed version: <<STUB>>/@sprucelabs/eslint-config-spruce_v^8.10.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sprucelabs/eslint-config-spruce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sprucelabs/eslint-config-spruce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@sprucelabs/eslint-config-spruce/index' {
  declare module.exports: $Exports<'@sprucelabs/eslint-config-spruce'>;
}
declare module '@sprucelabs/eslint-config-spruce/index.js' {
  declare module.exports: $Exports<'@sprucelabs/eslint-config-spruce'>;
}
