// flow-typed signature: 98f84a3d86cdadc4c67c8316f539abe4
// flow-typed version: <<STUB>>/@sprucelabs/heartwood-components_v^8.10.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sprucelabs/heartwood-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sprucelabs/heartwood-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sprucelabs/heartwood-components/build/components/raw/hamburger/hamburger' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/components/raw/sidebar/sidebar' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/01-button/button' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/01-button/context-menu' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/02-forms/09-checkbox/checkbox' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/02-forms/13-slider/slider' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/02-forms/autosuggest' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/02-forms/checkbox' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/02-forms/slider' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/03-structure/accordion' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/07-navigation/03-hamburger/hamburger' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/07-navigation/04-sidebar/sidebar' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/07-navigation/header-primary' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/99-web/01-navigation/01-hamburger/hamburger' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/99-web/01-navigation/02-sidebar/sidebar' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/js/99-web/header-primary' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/build/themes/mandelbrot/js/mandelbrot' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/01-button/01-primary-button/primary-button.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/01-button/02-secondary-button/secondary-button.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/01-button/03-simple-button/simple-button.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/01-button/04-caution-button/caution-button.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/01-button/05-small-buttons/small-buttons.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/01-button/06-full-width-buttons/full-width-buttons.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/01-button/07-button-group/button-group.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/01-button/08-context-menu/context-menu.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/01-button/button' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/01-button/context-menu' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/01-text-input/text-input.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/02-textarea/textarea.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/03-search/search.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/04-autosuggest/autosuggest.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/05-phone-input/phone-input.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/06-credit-card/credit-card.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/07-domain-input/domain-input.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/08-radio/radio.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/09-checkbox/checkbox.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/10-toggle/toggle.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/11-tag/tag.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/13-slider/slider.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/14-select/select.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/16-dropzone/dropzone.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/17-image-cropper/image-cropper.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/99-form-layout/form-layout.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/autosuggest' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/checkbox' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/form.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/02-forms/slider' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/03-structure/01-accordion/accordion.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/03-structure/02-layout/layout.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/03-structure/03-card/01-card-header/card-header.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/03-structure/03-card/03-card/card.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/03-structure/03-card/04-onboarding-card/onboarding-card.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/03-structure/04-page-components/01-page/page.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/03-structure/04-page-components/02-page-header/page-header.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/03-structure/04-page-components/03-page-content/page-content.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/03-structure/accordion' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/04-images-and-icons/01-avatar/avatar.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/05-feedback/01-toast/toast.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/06-modal/01-modal-header/modal-header.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/06-modal/02-modal-footer/modal-footer.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/07-navigation/01-tabs/tabs.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/07-navigation/02-pagination/pagination.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/08-lists/01-list-header/list-header.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/08-lists/02-text-list/text-list.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/08-lists/03-settings-list/settings-list.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/08-lists/04-people-list/people-list.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/08-lists/05-teams-list/teams-list.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/08-lists/06-services-list/services-list.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/08-lists/07-categories-list/categories-list.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/08-lists/08-special-events-list/special-events-list.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/08-lists/09-store-schedule-overrides/store-schedule-overrides.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/08-lists/10-schedule-availability/schedule-availability.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/09-bigcalendar/01-event-details-header/event-details-header.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/09-bigcalendar/02-event-details-footer/event-details-footer.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/09-bigcalendar/03-event-details/event-details.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/10-text/01-heading/heading.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/10-text/02-subheading/subheading.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/10-text/03-text/text.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/10-text/04-text-style/text-style.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/10-text/99-text-container/text-container.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/99-web/01-navigation/01-hamburger/hamburger.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/99-web/01-navigation/01-hamburger/hamburger' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/99-web/01-navigation/02-sidebar/sidebar.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/99-web/01-navigation/02-sidebar/sidebar' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/99-web/01-navigation/03-header-primary/header-primary.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/99-web/01-navigation/04-save-bar/save-bar.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/99-web/02-views/views.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/99-web/header-primary' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/feed/feed.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/main-preview.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/components/message/message.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/docs/02-styles/01-color.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/docs/03-components/01-buttons.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/docs/03-components/02-modals.config' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/fractal' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/Gulpfile' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/heartwood-components' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/01-button/button' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/01-button/context-menu' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/02-forms/09-checkbox/checkbox' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/02-forms/13-slider/slider' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/02-forms/autosuggest' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/02-forms/checkbox' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/02-forms/slider' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/03-structure/accordion' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/07-navigation/03-hamburger/hamburger' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/07-navigation/04-sidebar/sidebar' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/07-navigation/header-primary' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/99-web/01-navigation/01-hamburger/hamburger' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/99-web/01-navigation/02-sidebar/sidebar' {
  declare module.exports: any;
}

declare module '@sprucelabs/heartwood-components/public/js/99-web/header-primary' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sprucelabs/heartwood-components/build/components/raw/hamburger/hamburger.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/components/raw/hamburger/hamburger'>;
}
declare module '@sprucelabs/heartwood-components/build/components/raw/sidebar/sidebar.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/components/raw/sidebar/sidebar'>;
}
declare module '@sprucelabs/heartwood-components/build/js/01-button/button.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/01-button/button'>;
}
declare module '@sprucelabs/heartwood-components/build/js/01-button/context-menu.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/01-button/context-menu'>;
}
declare module '@sprucelabs/heartwood-components/build/js/02-forms/09-checkbox/checkbox.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/02-forms/09-checkbox/checkbox'>;
}
declare module '@sprucelabs/heartwood-components/build/js/02-forms/13-slider/slider.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/02-forms/13-slider/slider'>;
}
declare module '@sprucelabs/heartwood-components/build/js/02-forms/autosuggest.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/02-forms/autosuggest'>;
}
declare module '@sprucelabs/heartwood-components/build/js/02-forms/checkbox.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/02-forms/checkbox'>;
}
declare module '@sprucelabs/heartwood-components/build/js/02-forms/slider.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/02-forms/slider'>;
}
declare module '@sprucelabs/heartwood-components/build/js/03-structure/accordion.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/03-structure/accordion'>;
}
declare module '@sprucelabs/heartwood-components/build/js/07-navigation/03-hamburger/hamburger.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/07-navigation/03-hamburger/hamburger'>;
}
declare module '@sprucelabs/heartwood-components/build/js/07-navigation/04-sidebar/sidebar.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/07-navigation/04-sidebar/sidebar'>;
}
declare module '@sprucelabs/heartwood-components/build/js/07-navigation/header-primary.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/07-navigation/header-primary'>;
}
declare module '@sprucelabs/heartwood-components/build/js/99-web/01-navigation/01-hamburger/hamburger.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/99-web/01-navigation/01-hamburger/hamburger'>;
}
declare module '@sprucelabs/heartwood-components/build/js/99-web/01-navigation/02-sidebar/sidebar.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/99-web/01-navigation/02-sidebar/sidebar'>;
}
declare module '@sprucelabs/heartwood-components/build/js/99-web/header-primary.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/js/99-web/header-primary'>;
}
declare module '@sprucelabs/heartwood-components/build/themes/mandelbrot/js/mandelbrot.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/build/themes/mandelbrot/js/mandelbrot'>;
}
declare module '@sprucelabs/heartwood-components/components/01-button/01-primary-button/primary-button.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/01-button/01-primary-button/primary-button.config'>;
}
declare module '@sprucelabs/heartwood-components/components/01-button/02-secondary-button/secondary-button.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/01-button/02-secondary-button/secondary-button.config'>;
}
declare module '@sprucelabs/heartwood-components/components/01-button/03-simple-button/simple-button.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/01-button/03-simple-button/simple-button.config'>;
}
declare module '@sprucelabs/heartwood-components/components/01-button/04-caution-button/caution-button.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/01-button/04-caution-button/caution-button.config'>;
}
declare module '@sprucelabs/heartwood-components/components/01-button/05-small-buttons/small-buttons.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/01-button/05-small-buttons/small-buttons.config'>;
}
declare module '@sprucelabs/heartwood-components/components/01-button/06-full-width-buttons/full-width-buttons.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/01-button/06-full-width-buttons/full-width-buttons.config'>;
}
declare module '@sprucelabs/heartwood-components/components/01-button/07-button-group/button-group.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/01-button/07-button-group/button-group.config'>;
}
declare module '@sprucelabs/heartwood-components/components/01-button/08-context-menu/context-menu.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/01-button/08-context-menu/context-menu.config'>;
}
declare module '@sprucelabs/heartwood-components/components/01-button/button.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/01-button/button'>;
}
declare module '@sprucelabs/heartwood-components/components/01-button/context-menu.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/01-button/context-menu'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/01-text-input/text-input.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/01-text-input/text-input.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/02-textarea/textarea.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/02-textarea/textarea.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/03-search/search.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/03-search/search.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/04-autosuggest/autosuggest.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/04-autosuggest/autosuggest.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/05-phone-input/phone-input.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/05-phone-input/phone-input.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/06-credit-card/credit-card.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/06-credit-card/credit-card.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/07-domain-input/domain-input.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/07-domain-input/domain-input.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/08-radio/radio.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/08-radio/radio.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/09-checkbox/checkbox.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/09-checkbox/checkbox.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/10-toggle/toggle.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/10-toggle/toggle.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/11-tag/tag.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/11-tag/tag.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/13-slider/slider.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/13-slider/slider.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/14-select/select.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/14-select/select.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/16-dropzone/dropzone.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/16-dropzone/dropzone.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/17-image-cropper/image-cropper.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/17-image-cropper/image-cropper.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/99-form-layout/form-layout.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/99-form-layout/form-layout.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/autosuggest.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/autosuggest'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/checkbox.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/checkbox'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/form.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/form.config'>;
}
declare module '@sprucelabs/heartwood-components/components/02-forms/slider.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/02-forms/slider'>;
}
declare module '@sprucelabs/heartwood-components/components/03-structure/01-accordion/accordion.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/03-structure/01-accordion/accordion.config'>;
}
declare module '@sprucelabs/heartwood-components/components/03-structure/02-layout/layout.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/03-structure/02-layout/layout.config'>;
}
declare module '@sprucelabs/heartwood-components/components/03-structure/03-card/01-card-header/card-header.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/03-structure/03-card/01-card-header/card-header.config'>;
}
declare module '@sprucelabs/heartwood-components/components/03-structure/03-card/03-card/card.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/03-structure/03-card/03-card/card.config'>;
}
declare module '@sprucelabs/heartwood-components/components/03-structure/03-card/04-onboarding-card/onboarding-card.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/03-structure/03-card/04-onboarding-card/onboarding-card.config'>;
}
declare module '@sprucelabs/heartwood-components/components/03-structure/04-page-components/01-page/page.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/03-structure/04-page-components/01-page/page.config'>;
}
declare module '@sprucelabs/heartwood-components/components/03-structure/04-page-components/02-page-header/page-header.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/03-structure/04-page-components/02-page-header/page-header.config'>;
}
declare module '@sprucelabs/heartwood-components/components/03-structure/04-page-components/03-page-content/page-content.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/03-structure/04-page-components/03-page-content/page-content.config'>;
}
declare module '@sprucelabs/heartwood-components/components/03-structure/accordion.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/03-structure/accordion'>;
}
declare module '@sprucelabs/heartwood-components/components/04-images-and-icons/01-avatar/avatar.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/04-images-and-icons/01-avatar/avatar.config'>;
}
declare module '@sprucelabs/heartwood-components/components/05-feedback/01-toast/toast.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/05-feedback/01-toast/toast.config'>;
}
declare module '@sprucelabs/heartwood-components/components/06-modal/01-modal-header/modal-header.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/06-modal/01-modal-header/modal-header.config'>;
}
declare module '@sprucelabs/heartwood-components/components/06-modal/02-modal-footer/modal-footer.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/06-modal/02-modal-footer/modal-footer.config'>;
}
declare module '@sprucelabs/heartwood-components/components/07-navigation/01-tabs/tabs.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/07-navigation/01-tabs/tabs.config'>;
}
declare module '@sprucelabs/heartwood-components/components/07-navigation/02-pagination/pagination.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/07-navigation/02-pagination/pagination.config'>;
}
declare module '@sprucelabs/heartwood-components/components/08-lists/01-list-header/list-header.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/08-lists/01-list-header/list-header.config'>;
}
declare module '@sprucelabs/heartwood-components/components/08-lists/02-text-list/text-list.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/08-lists/02-text-list/text-list.config'>;
}
declare module '@sprucelabs/heartwood-components/components/08-lists/03-settings-list/settings-list.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/08-lists/03-settings-list/settings-list.config'>;
}
declare module '@sprucelabs/heartwood-components/components/08-lists/04-people-list/people-list.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/08-lists/04-people-list/people-list.config'>;
}
declare module '@sprucelabs/heartwood-components/components/08-lists/05-teams-list/teams-list.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/08-lists/05-teams-list/teams-list.config'>;
}
declare module '@sprucelabs/heartwood-components/components/08-lists/06-services-list/services-list.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/08-lists/06-services-list/services-list.config'>;
}
declare module '@sprucelabs/heartwood-components/components/08-lists/07-categories-list/categories-list.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/08-lists/07-categories-list/categories-list.config'>;
}
declare module '@sprucelabs/heartwood-components/components/08-lists/08-special-events-list/special-events-list.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/08-lists/08-special-events-list/special-events-list.config'>;
}
declare module '@sprucelabs/heartwood-components/components/08-lists/09-store-schedule-overrides/store-schedule-overrides.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/08-lists/09-store-schedule-overrides/store-schedule-overrides.config'>;
}
declare module '@sprucelabs/heartwood-components/components/08-lists/10-schedule-availability/schedule-availability.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/08-lists/10-schedule-availability/schedule-availability.config'>;
}
declare module '@sprucelabs/heartwood-components/components/09-bigcalendar/01-event-details-header/event-details-header.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/09-bigcalendar/01-event-details-header/event-details-header.config'>;
}
declare module '@sprucelabs/heartwood-components/components/09-bigcalendar/02-event-details-footer/event-details-footer.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/09-bigcalendar/02-event-details-footer/event-details-footer.config'>;
}
declare module '@sprucelabs/heartwood-components/components/09-bigcalendar/03-event-details/event-details.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/09-bigcalendar/03-event-details/event-details.config'>;
}
declare module '@sprucelabs/heartwood-components/components/10-text/01-heading/heading.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/10-text/01-heading/heading.config'>;
}
declare module '@sprucelabs/heartwood-components/components/10-text/02-subheading/subheading.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/10-text/02-subheading/subheading.config'>;
}
declare module '@sprucelabs/heartwood-components/components/10-text/03-text/text.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/10-text/03-text/text.config'>;
}
declare module '@sprucelabs/heartwood-components/components/10-text/04-text-style/text-style.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/10-text/04-text-style/text-style.config'>;
}
declare module '@sprucelabs/heartwood-components/components/10-text/99-text-container/text-container.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/10-text/99-text-container/text-container.config'>;
}
declare module '@sprucelabs/heartwood-components/components/99-web/01-navigation/01-hamburger/hamburger.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/99-web/01-navigation/01-hamburger/hamburger.config'>;
}
declare module '@sprucelabs/heartwood-components/components/99-web/01-navigation/01-hamburger/hamburger.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/99-web/01-navigation/01-hamburger/hamburger'>;
}
declare module '@sprucelabs/heartwood-components/components/99-web/01-navigation/02-sidebar/sidebar.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/99-web/01-navigation/02-sidebar/sidebar.config'>;
}
declare module '@sprucelabs/heartwood-components/components/99-web/01-navigation/02-sidebar/sidebar.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/99-web/01-navigation/02-sidebar/sidebar'>;
}
declare module '@sprucelabs/heartwood-components/components/99-web/01-navigation/03-header-primary/header-primary.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/99-web/01-navigation/03-header-primary/header-primary.config'>;
}
declare module '@sprucelabs/heartwood-components/components/99-web/01-navigation/04-save-bar/save-bar.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/99-web/01-navigation/04-save-bar/save-bar.config'>;
}
declare module '@sprucelabs/heartwood-components/components/99-web/02-views/views.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/99-web/02-views/views.config'>;
}
declare module '@sprucelabs/heartwood-components/components/99-web/header-primary.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/99-web/header-primary'>;
}
declare module '@sprucelabs/heartwood-components/components/feed/feed.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/feed/feed.config'>;
}
declare module '@sprucelabs/heartwood-components/components/main-preview.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/main-preview.config'>;
}
declare module '@sprucelabs/heartwood-components/components/message/message.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/components/message/message.config'>;
}
declare module '@sprucelabs/heartwood-components/docs/02-styles/01-color.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/docs/02-styles/01-color.config'>;
}
declare module '@sprucelabs/heartwood-components/docs/03-components/01-buttons.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/docs/03-components/01-buttons.config'>;
}
declare module '@sprucelabs/heartwood-components/docs/03-components/02-modals.config.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/docs/03-components/02-modals.config'>;
}
declare module '@sprucelabs/heartwood-components/fractal.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/fractal'>;
}
declare module '@sprucelabs/heartwood-components/Gulpfile.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/Gulpfile'>;
}
declare module '@sprucelabs/heartwood-components/heartwood-components.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/heartwood-components'>;
}
declare module '@sprucelabs/heartwood-components/public/js/01-button/button.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/01-button/button'>;
}
declare module '@sprucelabs/heartwood-components/public/js/01-button/context-menu.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/01-button/context-menu'>;
}
declare module '@sprucelabs/heartwood-components/public/js/02-forms/09-checkbox/checkbox.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/02-forms/09-checkbox/checkbox'>;
}
declare module '@sprucelabs/heartwood-components/public/js/02-forms/13-slider/slider.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/02-forms/13-slider/slider'>;
}
declare module '@sprucelabs/heartwood-components/public/js/02-forms/autosuggest.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/02-forms/autosuggest'>;
}
declare module '@sprucelabs/heartwood-components/public/js/02-forms/checkbox.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/02-forms/checkbox'>;
}
declare module '@sprucelabs/heartwood-components/public/js/02-forms/slider.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/02-forms/slider'>;
}
declare module '@sprucelabs/heartwood-components/public/js/03-structure/accordion.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/03-structure/accordion'>;
}
declare module '@sprucelabs/heartwood-components/public/js/07-navigation/03-hamburger/hamburger.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/07-navigation/03-hamburger/hamburger'>;
}
declare module '@sprucelabs/heartwood-components/public/js/07-navigation/04-sidebar/sidebar.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/07-navigation/04-sidebar/sidebar'>;
}
declare module '@sprucelabs/heartwood-components/public/js/07-navigation/header-primary.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/07-navigation/header-primary'>;
}
declare module '@sprucelabs/heartwood-components/public/js/99-web/01-navigation/01-hamburger/hamburger.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/99-web/01-navigation/01-hamburger/hamburger'>;
}
declare module '@sprucelabs/heartwood-components/public/js/99-web/01-navigation/02-sidebar/sidebar.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/99-web/01-navigation/02-sidebar/sidebar'>;
}
declare module '@sprucelabs/heartwood-components/public/js/99-web/header-primary.js' {
  declare module.exports: $Exports<'@sprucelabs/heartwood-components/public/js/99-web/header-primary'>;
}
